config/routes.rb
P1::Application.routes.draw do
  resources :links

  match 'pics/import' => 'pics#import'
  match 'pics/browse' => 'pics#browse'
  match 'pics/build_link/:id' => 'pics#build_link'
  
  resources :pics
  

  root :to => "pics#index"

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :pic
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.xml
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end

  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to(@link, :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to(@link, :notice => 'Link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  # GET /pics
  # GET /pics.xml
  def index
    @pics = Pic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pics }
    end
  end

  # GET /pics/1
  # GET /pics/1.xml
  def show
    @pic = Pic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.xml
  def new
    @pic = Pic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = Pic.find(params[:id])
  end

  # POST /pics
  # POST /pics.xml
  def create
    @pic = Pic.new(params[:pic])

    respond_to do |format|
      if @pic.save
        format.html { redirect_to(@pic, :notice => 'Pic was successfully created.') }
        format.xml  { render :xml => @pic, :status => :created, :location => @pic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.xml
  def update
    @pic = Pic.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to(@pic, :notice => 'Pic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.xml
  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to(pics_url) }
      format.xml  { head :ok }
    end
  end
  
  def browse
    @pic = Pic.find(params[:id]) 
    # @other_pics = Pic.find(:all, :order => 'weight DESC')
    links = @pic.links.find(:all,  :order => 'weight DESC')
    @other_pics = []
    links.each do |l|
      @other_pics << Pic.find(params[:id])
    end
    # debugger
    
    
    if @other_pics.size < 20 then 
      Pic.all.each do |p|
        @other_pics << p
      end
    end
    # @other_pics.each do |e|
    #   puts e.pic.id.to_s + " + " + e.weight.to_s
    # end
    # TODO - will need some proper size checking in here later (i.e. to match number of images with table dimensions)
    # puts @other_pics
    @max_table_width = 2
    
  end
  
  def build_link
    @pic = Pic.find(params[:id])
    from = Pic.find(session[:previous]) 
    puts "@pic "+@pic.id.to_s
    puts "from "+from.id.to_s
    if @pic.id == from.id
      then
    else
      @found ||= Link.where({:pic_id => from.id, :to_pic => @pic.id}).first
      if @found 
        @found.weight += 1
        @found.save
        else
        Link.new(:pic_id => from.id, :to_pic => @pic.id, :weight => 1).save
      end
    end
    redirect_to :controller => 'pics', :action  => 'browse', :id => @pic.id
  end
  
  def import
    basedir = "#{RAILS_ROOT}/public/import/"
    Dir.new(basedir).entries.each do |file|
      if File.directory? file
      else
        # puts file
        start = file.split('.')[0]
        if Pic.find_by_filename(start).blank?
          Pic.new(:filename => start).save
        else
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :pic_id %><br/>
		<%= f.text_field :pic_id %>
	</div>

  <div class="field">
    <%= f.label :to_pic %><br />
    <%= f.text_field :to_pic %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
	<th>From pic</th>
    <th>To pic</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.pic_id %></td>
    <td><%= link.to_pic %></td>
    <td><%= link.weight %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From pic:</b>
  <%= @link.pic_id %><br>
	<%= image_tag "/import/#{Pic.find(@link.pic_id).filename}.jpg", :border => 1%>
</p>

<p>
  <b>To pic:</b>
  <%= @link.to_pic %><br>
	<%= image_tag "/import/#{Pic.find(@link.to_pic).filename}.jpg", :border => 1%>
</p>

<p>
  <b>Weight:</b>
  <%= @link.weight %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/browse.html.erb
Came from pic.id = <%= @pic.id %>, which looks like this: <br>
<!-- # <%= image_tag "/import/#{@pic.filename}.jpg", :border => 1%><br> -->

<% session[:previous] = @pic.id %>

<%= puts "Params: " + params.to_s %>

<table>
	<tr><th>Images</th></tr>
	<% c = 0 %>
	<!-- <tr> -->
		<% @other_pics.each do |o| %>
		<!-- <td>	 -->
		<%= link_to image_tag("/import/#{o.filename}.jpg"), :controller => 'pics', :action => 'build_link', :id => o.id %>
		
		<!-- </td> -->
		<% if c > @max_table_width then puts c else c+=1 end%>
		<% end %>
	<!-- </tr> -->
	<!-- <tr> -->
		<% @other_pics.each do |o| %>
		<!-- <td> -->
		<!-- <%= link_to 'Detail', o %>	 -->
		<!-- </td> -->
		<% end %>
	<!-- </tr> -->
</table>

(Number of images = <%= @other_pics.size %>)

app/views/pics/build_link.html.erb
<p id="notice"><%= notice %></p>

Came from: <%= session[:previous] %><br>


<p>
  <b>Filename:</b>
  <%= @pic.filename %><br>
	<%= link_to image_tag("/set1/#{@pic.filename}.jpg", :border => 0), :controller => 'pics', :action => 'browse', :id => @pic.id %>

</p>


<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/import.html.erb
Files imported.
<%= link_to "Browse", pics_path %>
<%= link_to "Repeat import", pics_import_path %>

app/views/pics/index.html.erb
<h1>Listing pics</h1>

<table>
  <tr>
    <th>Filename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pics.each do |pic| %>
  <tr>
    <td><%= pic.filename %></td>
    <td><%= link_to image_tag("/import/#{pic.filename}.jpg"), :controller => 'pics', :action => 'browse', :id => pic.id %></td>
    <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
    <td><%= link_to 'Destroy', pic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

Came from: <%= session[:previous] %>

<p>
  <b>Filename:</b>
  <%= @pic.filename %><br>
	<%= link_to image_tag("/import/#{@pic.filename}.jpg", :border => 0), :controller => 'pics', :action => 'browse', :id => @pic.id %>

</p>


<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>